"""Add visual-only E1 Unity layers from the existing P1L2 viewer export.

This script does not recalculate gravity. It appends only top-level visual fields
to `results/edificio1_unity.json`: columns, walls, supports and diaphragms.
Existing slabs, beams, tributaries, qG, P, w and QA are verified unchanged by
object comparison before/after excluding the new keys.
"""

from __future__ import annotations

import copy
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


UNITY_ROOT = Path(__file__).resolve().parent
REPO_ROOT = UNITY_ROOT.parents[2]
E1_JSON = REPO_ROOT / "entregas" / "semana2_gravedad" / "results" / "edificio1_unity.json"
P1L2_REF = "origin/main:entregas/P1L2/unity_export/model_viewer.json"
VISUAL_KEYS = ("columns", "walls", "supports", "diaphragms")
FLOOR_ID = {"base": 0, "1S": -1, "1": 1, "2": 2, "3": 3, "4": 4}


def git_show_json(ref_path: str) -> dict[str, Any]:
    completed = subprocess.run(
        ["git", "show", ref_path],
        cwd=REPO_ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    return json.loads(completed.stdout)


def section(width: float | None, depth: float | None) -> dict[str, float]:
    out: dict[str, float] = {}
    if width is not None:
        out["width_m"] = width
    if depth is not None:
        out["height_m"] = depth
    return out


def solid_common(solid: dict[str, Any], category: str) -> dict[str, Any]:
    floor = str(solid.get("floor"))
    return {
        "id": solid.get("solidTag"),
        f"{category}_id": solid.get("solidTag"),
        "category": category,
        "kind": solid.get("kind"),
        "floor": floor,
        "floor_id": FLOOR_ID[floor],
        "sourceTag": solid.get("sourceTag"),
        "source_layer": solid.get("source_layer"),
        "source_dxf": solid.get("source_dxf"),
        "confidence": solid.get("confidence"),
        "visual_source": "origin/main:entregas/P1L2/unity_export/model_viewer.json",
        "width_m": solid.get("width_m"),
        "height_m": solid.get("height_m"),
        "depth_m": solid.get("depth_m"),
        "length_m": solid.get("length_m"),
        "section": section(solid.get("width_m"), solid.get("depth_m") or solid.get("width_m")),
    }


def convert_column(solid: dict[str, Any]) -> dict[str, Any]:
    item = solid_common(solid, "column")
    center = solid.get("center") or [0.0, 0.0, 0.0]
    height = float(solid.get("height_m") or solid.get("length_m") or 0.0)
    z = float(center[2]) if len(center) >= 3 else 0.0
    item.update(
        {
            "center": center,
            "node_i": [center[0], center[1], z - height / 2.0],
            "node_j": [center[0], center[1], z + height / 2.0],
            "implementation": "box column from P1L2 CAD solid; node_i/node_j are visual base/top",
        }
    )
    return item


def convert_wall(solid: dict[str, Any]) -> dict[str, Any]:
    item = solid_common(solid, "wall")
    item.update(
        {
            "node_i": solid.get("start"),
            "node_j": solid.get("end"),
            "implementation": "vertical wall panel from P1L2 merged CAD wall segment",
            "notes": "wall thickness uses width_m when available",
        }
    )
    return item


def convert_support(solid: dict[str, Any]) -> dict[str, Any]:
    item = solid_common(solid, "support")
    item.update(
        {
            "node_i": solid.get("start"),
            "node_j": solid.get("end"),
            "implementation": "base support visual generated by P1L2 connected-support layer",
            "notes": "restrained_dofs are not explicit in the source JSON",
        }
    )
    return item


def convert_diaphragm(diaphragm: dict[str, Any], index: int) -> dict[str, Any]:
    floor = str(diaphragm.get("floor"))
    floor_id = FLOOR_ID[floor]
    return {
        "id": f"E1_F{floor.replace('1S', '1S').zfill(2) if floor.isdigit() else floor}_D{index:03d}",
        "diaphragm_id": f"E1_F{floor}_D{index:03d}",
        "category": "diaphragm",
        "kind": "floor_polygon",
        "floor": floor,
        "floor_id": floor_id,
        "points": diaphragm.get("points", []),
        "vertices": diaphragm.get("points", []),
        "visual_source": "origin/main:entregas/P1L2/unity_export/model_viewer.json",
        "implementation": "visual rigid diaphragm polygon per floor from P1L2 viewer export",
        "notes": "master_node/slave_nodes are not explicit in the source JSON",
    }


def strip_visual(data: dict[str, Any]) -> dict[str, Any]:
    clean = copy.deepcopy(data)
    for key in VISUAL_KEYS:
        clean.pop(key, None)
    return clean


def field_text(key: str, value: Any) -> str:
    return f'  "{key}": ' + json.dumps(value, indent=2, ensure_ascii=False).replace("\n", "\n  ")


def insert_visual_fields(original_text: str, fields: dict[str, Any]) -> str:
    marker = "\n}"
    pos = original_text.rfind(marker)
    if pos < 0:
        raise ValueError("JSON root closing brace not found")
    prefix = original_text[:pos].rstrip()
    suffix = original_text[pos:]
    chunks = [field_text(key, fields[key]) for key in VISUAL_KEYS]
    return prefix + ",\n" + ",\n".join(chunks) + suffix


def main() -> None:
    original_text = E1_JSON.read_text(encoding="utf-8")
    original_data = json.loads(original_text)
    original_without_visual = strip_visual(original_data)

    p1l2 = git_show_json(P1L2_REF)
    solids = p1l2.get("solids", [])
    columns = [convert_column(s) for s in solids if s.get("category") == "column" and s.get("floor") in {"1S", "1", "2", "3", "4"}]
    walls = [convert_wall(s) for s in solids if s.get("category") == "wall" and s.get("floor") in {"1S", "1", "2", "3", "4"}]
    supports = [convert_support(s) for s in solids if s.get("category") == "support" and s.get("floor") == "base"]
    diaphragms = [convert_diaphragm(d, i) for i, d in enumerate(p1l2.get("diaphragms", []), start=1) if d.get("floor") in {"1S", "1", "2", "3", "4"}]

    fields = {
        "columns": columns,
        "walls": walls,
        "supports": supports,
        "diaphragms": diaphragms,
    }

    text_without_visual = original_text
    if any(key in original_data for key in VISUAL_KEYS):
        data = strip_visual(original_data)
        text_without_visual = json.dumps(data, indent=2, ensure_ascii=False)

    updated_text = insert_visual_fields(text_without_visual, fields)
    updated_data = json.loads(updated_text)
    if strip_visual(updated_data) != original_without_visual:
        print("visual extension FAIL: existing gravity/model fields changed", file=sys.stderr)
        sys.exit(1)

    E1_JSON.write_text(updated_text + ("" if updated_text.endswith("\n") else "\n"), encoding="utf-8")
    print(
        "visual extension OK: "
        f"columns={len(columns)} walls={len(walls)} "
        f"supports={len(supports)} diaphragms={len(diaphragms)}"
    )


if __name__ == "__main__":
    main()
